name: Mock Interview CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use whatever version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint checks (flake8)
      run: |
        pip install flake8
        flake8 .

    - name: Run basic tests (optional)
      run: |
        echo "No tests yet"  # replace with pytest or unittests when available
